### ISSUE TITLE
Unable to view map legend on MacOS?

### ISSUE THREAD

**Issue by mcdent** [ttnmapper/bugtracker#17] opened 2022-07-02 18:01 UTC
Oddly I cannot see the legend for heat map under MacOS with both Chrome and Safari.
I am using MacOS 12.4.
I've tried with all the different map overlays too.
I have tried with the windows maximised too, I assume it should 'just' appear in the lower right corner? 
See attached.
![Screenshot 2022-07-02 at 19 00 42](https://user-images.githubusercontent.com/8769856/177011552-8a7a6fbb-f21e-4164-ae0e-f892510d91e8.jpg)
![Screenshot 2022-07-02 at 19 00 13](https://user-images.githubusercontent.com/8769856/177011554-76e0d7c1-e0bd-4a85-8343-eae5d303001f.jpg)

**Comment by jpmeijers** [comment] 2022-07-03 15:42
You are correct that the legend should appear in the lower right hand corner. It is automatically hidden on mobile browsers because there is normally not enough space to show it. So for some reason the logic is detecting your device as a mobile device, and hiding this legend.

If you can give me your browser's user agent string that might help identify the issue. A quick google resulted in this page that can help to get the user agent: https://www.whatismybrowser.com/detect/what-is-my-user-agent/

Are you perhaps on an iPad?

**Comment by mcdent** [comment] 2022-07-03 15:46
I'm not on an iPad, Mac running MacOS.
So the browser string for Safari is:-
[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)

For Chrome it is:-
[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)

I hope that helps.

**Comment by jpmeijers** [comment] 2022-07-03 15:54
That does not seem to be the cause. I've checked the code and the legend on coveragemap.net is always shown on the heatmap.

Could you open the developer console and see if there are any error messages printed there?
In Chrome: Three dots upper right, More tools, Developer Tools. And then choose the Console tab. ex:
![image](https://user-images.githubusercontent.com/948278/177047391-2817323e-7d9f-4adb-aa64-6f6dc44362cb.png)

**Comment by mcdent** [comment] 2022-07-03 16:00
Ok, here is the display on Chrome:-
![Screenshot 2022-07-03 at 17 00 09](https://user-images.githubusercontent.com/8769856/177047625-26aed0c5-25ea-4d06-9af2-95c92183fe07.jpg)

**Comment by jpmeijers** [comment] 2022-07-03 16:09
Ah great, that helps. Thanks!

We can see it is definitely detecting it as a mobile browser, so that must be the reason. My previous assumption was clearly invalid. I'll debug further and see if I can find the problem.

```
Mobile Browser
false false true true
```
is printed by
```
    console.log("Mobile Browser");
    console.log(L.Browser.android, L.Browser.mobile, L.Browser.touch, L.Browser.retina);
```
* Android: no
* Mobile: no
* Touch: yes
* Retina: yes

Ahh and here is the bug:
```  if (L.Browser.android || L.Browser.mobile /*|| L.Browser.touch*/ || L.Browser.retina) {```
That `if` is detecting `retina` as mobile.

**Comment by jpmeijers** [comment] 2022-07-03 16:14
Ok fix is deployed. You might need to force refresh the page, or wait until your browser cache has expired. Maybe try in incognito mode and see if it is fixed please.

**Comment by mcdent** [comment] 2022-07-03 16:19
Yes, looks good now, thank you!
Whilst I have you, can I ask what the meaning of the colours round the main centre colour is?
![Screenshot 2022-07-03 at 17 18 37](https://user-images.githubusercontent.com/8769856/177048327-63c8847e-65c2-4b6e-b413-3059c0ad2320.jpg)

**Comment by jpmeijers** [comment] 2022-07-03 16:23
Great!

Fixed by https://github.com/ttnmapper/coveragemap-website/commit/45b8306d4f42b5ba4710eed278344a032dbd0e46

Your second question, I tried to explain it in my talk here:
https://youtu.be/Y9lMvyTYI3E?t=890

If it's not clear, let me know and I'll try and document it better somewhere.

**Closed as completed by jpmeijers** 2022-07-03 16:23 UTC
